- name: configure cart service
  hosts: cart
  become: yes
  tasks:
    - name: Disable default nodejs module
      ansible.builtin.command: dnf module disable nodejs -y
    - name: Enable required nodejs module
      ansible.builtin.command: dnf module enable nodejs:20 -y
    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: Create application user
      ansible.builtin.user:
        name: roboshop
        state: present
        shell: /sbin/nologin
        home: /app
        system: yes
    - name: Create application directory
      ansible.builtin.file:
        name: /app
        state: directory
    - name: Download cart code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip
    - name: Unzip cart code
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes
    - name: Install npm dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
    - name: Copy systemd service file
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service
    - name: System deamon reload
      ansible.builtin.systemd:
        daemon_reload: true
    - name: Start and Enable cart service
      ansible.builtin.service:
        name: cart
        state: started
        enabled: yes
