- name: configure user service
  hosts: user
  become: yes
  tasks:
    - name: Disable default nodejs module
      ansible.builtin.command: dnf module disable nodejs -y
    - name: Enable required nodejs module
      ansible.builtin.command: dnf module enable nodejs:20 -y
    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: Create application user
      ansible.builtin.user:
        name: roboshop
        state: present
        shell: /sbin/nologin
        home: /app
    - name: Create application directory
      ansible.builtin.file:
        name: /app
        state: directory
    - name: Download user code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /tmp/user.zip
    - name: Unzip user code
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src: yes
    - name: Install npm dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
    - name: Copy systemd service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service
    - name: System deamon reload
      ansible.builtin.systemd.service:
        daemon_reload: true
    - name: Start and Enable user service
      ansible.builtin.service:
        name: user
        state: started
        enabled: yes
